apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
#- github.com/utilitywarehouse/docker-registry-manifests//base?ref=v1.1.2
resources:
  - registry-ingress.yaml
patchesStrategicMerge:
  - registry-patch.yaml
secretGenerator:
  - name: registry
    env: secrets/credentials
    type: Opaque
  - name: registry-nginx
    files:
      - secrets/htpasswd
    type: Opaque
