apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
#- github.com/utilitywarehouse/docker-registry-manifests//base?ref=1.1.0
resources:
  - registry-ingress.yaml
patchesStrategicMerge:
  - registry-patch.yaml
configMapGenerator:
  - name: registry-frontend
    behavior: merge
    files:
      - config.yml=resources/frontend-config.yml
secretGenerator:
  - name: registry
    envs:
      - secrets/credentials
    files:
      - registry_notifications_endpoints=secrets/notifications.yaml
    type: Opaque
  - name: registry-auth
    files:
      - secrets/auth_config.yml
    type: Opaque
  - name: registry-frontend
    envs:
      - secrets/registry-frontend
    files:
      - config.yml=secrets/frontend-config.yml
    type: Opaque
