apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
#- github.com/utilitywarehouse/docker-registry-manifests//base?ref=1.1.0
resources:
  - registry-ingress.yaml
patchesStrategicMerge:
  - registry-patch.yaml
secretGenerator:
  - name: registry
    envs:
      - secrets/credentials
    type: Opaque
  - name: registry-auth-cert
    files:
      - secrets/tls.crt
      - secrets/tls.key
    type: kubernetes.io/tls
  - name: registry-auth
    files:
      - secrets/auth_config.yml
    type: Opaque
