apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    kubernetes.io/ingress.class: traefik-public-tls
  annotations:
    external-dns.alpha.kubernetes.io/target: public.example.com
  name: docker-registry
spec:
  rules:
    - host: registry.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: docker-registry
              servicePort: 5000
          - path: /auth
            backend:
              serviceName: docker-registry
              servicePort: 5001
