apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
spec:
  template:
    spec:
      containers:
        - name: docker-registry
          env:
            - name: REGISTRY_AUTH_TOKEN_REALM
              value: "https://registry.example.com/auth"
            - name: REGISTRY_AUTH_TOKEN_ISSUER
              value: "example.com"
            - name: REGISTRY_STORAGE_S3_BUCKET
              value: "example-bucket"
            - name: REGISTRY_STORAGE_S3_REGION
              value: "eu-west-1"
            - name: REGISTRY_STORAGE_S3_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: registry
                  key: registry_storage_s3_accesskey
            - name: REGISTRY_STORAGE_S3_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: registry
                  key: registry_storage_s3_secretkey
            - name: REGISTRY_HTTP_SECRET
              valueFrom:
                secretKeyRef:
                  name: registry
                  key: registry_http_secret
            - name: REGISTRY_NOTIFICATIONS_ENDPOINTS
              valueFrom:
                secretKeyRef:
                  name: registry
                  key: registry_notifications_endpoints
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: docker-registry-frontend
spec:
  template:
    spec:
      initContainers:
        - name: frontend-config
          env:
            - name: EVENT_LISTENER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: registry-frontend
                  key: event_listener_token
      containers:
        - name: oauth
          env:
            - name: OAUTH2_PROXY_REDIRECT_URL
              value: "https://example.com/oauth2/callback"
            - name: OAUTH2_PROXY_CLIENT_ID
              value: "CLIENT_ID.apps.googleusercontent.com"
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: registry-frontend
                  key: oauth_proxy_client_secret
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: registry-frontend
                  key: oauth_proxy_cookie_secret
            - name: OAUTH2_PROXY_EMAIL_DOMAINS
              value: "example.com"
        - name: docker-registry
          env:
            - name: REGISTRY_STORAGE_S3_BUCKET
              value: "uw-dev-sys-registry"
            - name: REGISTRY_STORAGE_S3_REGION
              value: "eu-west-1"
            - name: REGISTRY_STORAGE_S3_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: registry
                  key: registry_storage_s3_accesskey
            - name: REGISTRY_STORAGE_S3_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: registry
                  key: registry_storage_s3_secretkey
