apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
spec:
  template:
    spec:
      containers:
        - name: docker-registry
          env:
            - name: REGISTRY_STORAGE_S3_BUCKET
              value: "example-bucket"
            - name: REGISTRY_STORAGE_S3_REGION
              value: "eu-west-1"
            - name: REGISTRY_STORAGE_S3_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: registry
                  key: registry_storage_s3_accesskey
            - name: REGISTRY_STORAGE_S3_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: registry
                  key: registry_storage_s3_secretkey
            - name: REGISTRY_HTTP_SECRET
              valueFrom:
                secretKeyRef:
                  name: registry
                  key: registry_http_secret
        - name: docker-registry-frontend
          env:
            - name: ENV_REGISTRY_PROXY_FQDN
              value: "registry-browser.example.com"
