apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - registry.yaml
  - registry-auth-cert-rotator.yaml
configMapGenerator:
  - name: registry
    files:
      - resources/config.yml
  - name: registry-auth-cert-rotator
    files:
      - resources/cert-rotator.sh
