apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - registry.yaml
configMapGenerator:
  - name: registry
    files:
      - conf/config.yml
  - name: registry-nginx
    files:
      - conf/nginx.conf
