apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - registry-cert-reloader.yaml
  - registry.yaml
configMapGenerator:
  - name: registry-cert-reloader
    files:
      - resources/cert-reloader.sh
  - name: registry
    files:
      - resources/config.yml
