apiVersion: v1
kind: Service
metadata:
  annotations:
    ingress.kubernetes.io/affinity: "true"
    traefik.backend.loadbalancer.stickiness: "true"
  labels:
    name: docker-registry-frontend
  name: docker-registry-frontend
spec:
  selector:
    app: docker-registry-frontend
  ports:
    - name: frontend
      protocol: TCP
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry-frontend
  template:
    metadata:
      name: docker-registry-frontend
      labels:
        app: docker-registry-frontend
    spec:
      containers:
        - name: docker-registry
          image: registry:2.7.1
          resources:
            requests:
              cpu: 0m
              memory: 32Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: registry-config
              mountPath: /etc/docker/registry/
              readOnly: true
        - name: docker-registry-frontend
          image: konradkleine/docker-registry-frontend:v2
          resources:
            requests:
              cpu: 0m
              memory: 4Mi
            limits:
              cpu: 100m
              memory: 128Mi
          env:
            - name: ENV_DOCKER_REGISTRY_HOST
              value: "localhost"
            - name: ENV_DOCKER_REGISTRY_PORT
              value: "5000"
            - name: ENV_REGISTRY_PROXY_PORT
              value: "443"
          ports:
            - name: frontend
              containerPort: 80
      volumes:
        - name: registry-config
          configMap:
            name: registry-frontend
            items:
              - key: config.yml
                path: config.yml
