# Registry v2.1 comes with features like
# "Some config values can be set from the environment, but not if
# contradictory settings are in the config.yml". We use this as a
# config data volume to attach to the registry so we can override with
# ENV variables.
version: 0.1
log:
  accesslog:
    disabled: true
  level: warn
  fields:
    service: registry
storage:
  s3:
    encrypt: true
  maintenance:
    readonly:
      enabled: true
http:
  addr: localhost:5000
