# Registry v2.1 comes with features like
# "Some config values can be set from the environment, but not if
# contradictory settings are in the config.yml". We use this as a
# config data volume to attach to the registry so we can override with
# ENV variables from Ansible.
version: 0.1
log:
  accesslog:
    disabled: true
  level: warn
  fields:
    service: registry
storage:
  s3:
    encrypt: true
  delete:
    enabled: true
http:
  addr: :5000
auth:
  token:
    service: registry
    rootcertbundle: /etc/tls/tls.crt
